spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Hello"
  default-value: "World"

spring:
  application:
    name: book-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
spring:
  application:
    name: cambio-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'